{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Sentence aligner API"
  },
  "tags": [
    {
      "name": "sentences",
      "description": "Operations on sentences"
    },
    {
      "name": "languages",
      "description": "Operations on languages"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/sentences": {
      "post": {
        "tags": [
          "sentences"
        ],
        "summary": "Create a new sentence.",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "The sentence object that has to be created.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Sentence"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "The sentence has been created."
          },
          "409": {
            "description": "The given UUID is already used by another sentence or both of the language and content are already used by another sentence."
          }
        }
      },
      "get": {
        "tags": [
          "sentences"
        ],
        "summary": "Get all the sentences.",
        "parameters": [
          {
            "in": "query",
            "required": true,
            "name": "starting_after_id",
            "schema": {
              "type": "uuid"
            },
            "description": "last uuid for pagination"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns all the sentences.",
            "schema": {
              "$ref": "#/definitions/sentences"
            },
            "examples": {
              "application/json": [
                {
                  "id": "4491-808e-405d-9fdd-0e853a383bcc",
                  "text": "It rains.",
                  "iso639_3": "eng",
                  "structure": "<sentence><subject>It</subject> <verb>rains</verb>.</sentence>"
                }
              ]
            }
          }
        }
      }
    },
    "/sentences/{sentence_id}": {
      "get": {
        "tags": [
          "sentences"
        ],
        "summary": "Returns one sentence properties.",
        "parameters": [
          {
            "name": "sentence_id",
            "in": "path",
            "description": "The sentence UUID.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Succeed. Returns the requested sentence content.",
            "schema": {
              "$ref": "#/definitions/Sentence"
            },
            "examples": {
              "application/json": {
                "id": "4491-808e-405d-9fdd-0e853a383bcc",
                "text": "It rains.",
                "iso639_3": "eng",
                "structure": "<sentence><subject>It</subject> <verb>rains</verb>.</sentence>"
              }
            }
          },
          "404": {
            "description": "The requested sentence cannot be found."
          }
        }
      }
    },
    "/sentences/{sentence_id}/text": {
      "put": {
        "tags": [
          "sentences"
        ],
        "summary": "Update the content of one sentence.",
        "parameters": [
          {
            "name": "sentence_id",
            "in": "path",
            "description": "The sentence UUID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "description": "The new sentence content.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SentenceContent"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Succeed. The sentence content has been updated."
          },
          "404": {
            "description": "The requested sentence cannot be found."
          },
          "409": {
            "description": "A sentence with the same content and the same language already exists."
          }
        }
      }
    },
    "/sentences/{sentence_id}/structure": {
      "put": {
        "tags": [
          "sentences"
        ],
        "summary": "Update the structure of one sentence.",
        "parameters": [
          {
            "name": "sentence_id",
            "in": "path",
            "description": "The sentence UUID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "description": "The new sentence structure.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SentenceStructure"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Succeed. The sentence structure has been updated."
          },
          "400": {
            "description": "The sent structure does not match with the sentence content."
          },
          "404": {
            "description": "The requested sentence cannot be found."
          }
        }
      }
    },
    "/sentences/{sentence_id}/language": {
      "put": {
        "tags": [
          "sentences"
        ],
        "summary": "Update the language of one sentence.",
        "parameters": [
          {
            "name": "sentence_id",
            "in": "path",
            "description": "The sentence UUID.",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "description": "The new sentence language.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SentenceLanguage"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Succeed. The sentence language has been updated."
          },
          "404": {
            "description": "The requested sentence or the language cannot be found."
          },
          "409": {
            "description": "A sentence with identical language and content than the edited sentence already exists."
          }
        }
      }
    },
    "/languages/{language}/sentences": {
      "get": {
        "tags": [
          "sentences"
        ],
        "summary": "Get all the sentences with the given language.",
        "parameters": [
          {
            "name": "language",
            "in": "path",
            "description": "The language used to filter sentences (iso 639-3 format).",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns all the sentences with the given language.",
            "schema": {
              "$ref": "#/definitions/sentences"
            },
            "examples": {
              "application/json": [
                {
                  "id": "4491-808e-405d-9fdd-0e853a383bcc",
                  "text": "It rains.",
                  "iso639_3": "eng",
                  "structure": "<sentence><subject>It</subject> <verb>rains</verb>.</sentence>"
                }
              ]
            }
          }
        }
      }
    },
    "/languages": {
      "post": {
        "tags": [
          "languages"
        ],
        "summary": "Create one language.",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "The language that has to be created.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Language"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "The language has been created."
          },
          "409": {
            "description": "The language already exists."
          }
        }
      }
    }
  },
  "definitions": {
    "Sentence": {
      "type": "object",
      "required": [
        "text",
        "iso639_3"
      ],
      "properties": {
        "id": {
          "type": "string",
          "example": "313a4491-808e-405d-9fdd-0e853a383bcc"
        },
        "text": {
          "$ref": "#/definitions/SentenceContent"
        },
        "iso639_3": {
          "$ref": "#/definitions/SentenceLanguage"
        },
        "structure": {
          "$ref": "#/definitions/SentenceStructure"
        }
      }
    },
    "SentenceContent": {
      "type": "string",
      "example": "It rains."
    },
    "SentenceLanguage": {
      "type": "string",
      "example": "eng"
    },
    "SentenceStructure": {
      "type": "string",
      "example": "<sentence><subject>It</subject> <verb>rains</verb>.</sentence>"
    },
    "sentences": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Sentence"
      }
    },
    "Language": {
      "type": "string",
      "example": "eng"
    }
  }
}
